/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'SendJoiningLetter': EventHandler<never, never>
    'GenerateWorkCredentials': EventHandler<never, { topic: 'credentials.generated'; data: never }>
    'ReceiveKitConfirmation': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'kit.received'; data: never }>
    'SendKitDispatchedMail': EventHandler<never, never>
    'OrderWelcomeKit': EventHandler<never, { topic: 'kit.ordered'; data: never }>
    'ReceiveDetails': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'details.received'; data: never }>
    'SendDetailFormEmail': EventHandler<never, never>
    'VerificationFailed': EventHandler<never, never>
    'VerificationPassed': EventHandler<never, { topic: 'verification.passed.email.sent'; data: never }>
    'GeminiOCR': EventHandler<never, { topic: 'verification.passed'; data: never } | { topic: 'verification.failed'; data: never }>
    'SendDocumentRetry': EventHandler<never, never>
    'SendStep1SuccessMail': EventHandler<never, { topic: 'step1.success.sent'; data: never }>
    'FetchDriveFiles': EventHandler<never, { topic: 'files.fetched'; data: never } | { topic: 'documents.retry'; data: never }>
    'ReceiveDocuments': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'documents.received'; data: never }>
    'SendDocumentRequest': EventHandler<never, never>
    'SendNoStatusMail': EventHandler<never, never>
    'SendYesStatusMail': EventHandler<never, { topic: 'offer.accepted'; data: never }>
    'HandleOfferResponse': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'offer.response.received'; data: never }>
    'SendJoiningMail': EventHandler<never, never>
    'ReceiveEmployeeData': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'employee.data.received'; data: never }>
  }
    
}